### ISSUE TITLE
Unable to login into Auth0 account after signup

### ISSUE THREAD

**Issue by bhanuprasad04** [xcv58/meteor-auth0#6]
I have added your package in  my meteor application and i am able to see the Auth0 popup.When I click on signup and enter all the details, then click on submit button, User created in Auth0 account but unable to login.It's ended with below error 
**signed up successful but couldn't log in** 
What could be the wrong? AM I missing anything here?.
Could you please help me on this .

**Comment by xcv58** [comment]
I'd like to help you. However, I don't have enough information to give you suggestion.

1. What's your Meteor version and `xcv58:auth0-lock` version?
2. Do you have a reproduce repo?
3. Could you please make sure your Auth0 client settings are correct, i.e. allowed web origins, callbacks, etc.?

And there is an example in this repo: https://github.com/xcv58/meteor-auth0/blob/master/README.md#example

Please let me know whether you can reproduce the problem with the example app.

**Comment by bhanuprasad04** [comment]
Thanks for the replay.
Below are the details and versions which I am using in my local .
meteor --version
Meteor 1.6.1
xcv58:auth0-lock                         6.0.2* Auth0 Lock for Meteor
**ClientSettings**:
weborigins URL: http://localhost:3000
CallBack URL    : http://localhost:3000

Did I missed out anything?
Do you want me to check anything else.I'M able to see the created users in the Auth0 users list.
please help me.

**Comment by xcv58** [comment]
The `v6.0.2` is really old with outdated auth0-lock version. Could you please upgrade to `7.1.0` and try again?

**Comment by bhanuprasad04** [comment]
Hi I'M very new to meteor, How can i add 7.1.0. When I'M trying to add the package like below by default it is giving v6.0.2
meteor add xcv58:auth0-lock.

**Comment by bhanuprasad04** [comment]
Thanks for the help, After upgrade my package to 7.1.0, It is working perfectly fine.Thank you so much

**Comment by xcv58** [comment]
You are welcome!
